import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Fingerprint, Info, Play, Square } from "lucide-react";
import RunHistory, { fetchStoredWorkflow, useRunHistory } from "../components/shared/RunHistory";
import SourceList from "../components/shared/SourceList";
import WorkstreamLanes from "../components/shared/WorkstreamLanes";
import { useWorkflowStream } from "../hooks/useWorkflowStream";
import { MerchantEvidence, MerchantRiskResult, WorkflowLaneDefinition } from "../types";

const MERCHANT_LANES: WorkflowLaneDefinition[] = [
  { id: "identity", label: "1 · Resolve merchant identity" }, { id: "category_fit", label: "2 · Category fit" }, { id: "restricted_products", label: "2 · Restricted products" }, { id: "reputation", label: "2 · Reputation & practices" }, { id: "legal_regulatory", label: "2 · Legal & regulatory" },
];
const fieldClass="glass-input rounded-xl px-3 py-2.5 text-sm text-ink-100 placeholder:text-ink-500 outline-none focus:ring-2 focus:ring-tavily-blue/20 w-full";
const List=({items,empty}:{items?:string[];empty?:string}) => items?.length ? <ul className="space-y-2">{items.map((item,index)=><li className="text-sm text-ink-300 flex gap-2" key={index}><span className="text-tavily-blue">•</span><span>{item}</span></li>)}</ul> : empty ? <p className="text-xs text-ink-500 italic">{empty}</p> : null;
function EvidenceCards({items}:{items?:MerchantEvidence[]}) { if(!items?.length)return null; return <div className="space-y-2">{items.map((item,index)=><article key={`${item.finding}-${index}`} className="glass-subtle rounded-xl p-3"><h4 className="text-sm font-semibold text-ink-100">{item.finding}</h4><p className="text-xs text-ink-400 leading-relaxed mt-1">{item.significance}</p>{item.observed_date&&<p className="text-[10px] text-ink-500 mt-2">Observed {item.observed_date}</p>}<div className="flex flex-wrap gap-2 mt-2">{item.source_urls.map((url,i)=><a key={url} href={url} target="_blank" rel="noreferrer" className="text-[10px] text-tavily-blue hover:underline">Evidence {i+1}</a>)}</div></article>)}</div>; }
function Metric({label,value}:{label:string;value:string}) { return <div className="glass-subtle rounded-xl p-3"><p className="text-[10px] uppercase tracking-wider text-ink-500">{label}</p><p className="text-sm font-semibold text-ink-100 mt-1 capitalize">{value.replace(/_/g," ")}</p></div>; }
function ReportList({title,items,empty}:{title:string;items?:string[];empty:string}) {return <section className="glass rounded-xl p-4"><h3 className="font-display text-sm font-semibold text-ink-100 mb-3">{title}</h3><List items={items} empty={empty}/></section>;}
function RiskReport({result}:{result:MerchantRiskResult}) { const identity=result.resolved_identity; return <section className="space-y-5"><div className="glass rounded-2xl p-6"><div className="text-risk-low text-xs font-semibold uppercase tracking-wider flex gap-2 items-center"><CheckCircle2 className="w-4 h-4"/>Public-web context assembled</div><h2 className="font-display text-2xl font-semibold text-ink-100 mt-3">{identity?.canonical_name || result.merchant_name}</h2><p className="text-xs text-ink-500 mt-1">Submitted category: {result.category_code}</p><div className="grid sm:grid-cols-3 gap-3 mt-5"><Metric label="Web-context level" value={result.web_context_level}/><Metric label="Identity confidence" value={result.identity_confidence}/><Metric label="Evidence coverage" value={result.evidence_coverage}/></div>
  {identity && <div className="mt-5 pt-5 border-t border-white/50"><h3 className="font-display font-semibold text-ink-100 flex gap-2"><Fingerprint className="w-4 h-4 text-tavily-blue"/>Resolved identity</h3><div className="grid sm:grid-cols-2 gap-2 text-sm mt-3"><p><span className="text-ink-500">Domain: </span>{identity.canonical_domain || "Unverified"}</p><p><span className="text-ink-500">Country: </span>{identity.country || "Unverified"}</p></div>{identity.business_description&&<p className="text-sm text-ink-300 mt-3">{identity.business_description}</p>}<div className="mt-3"><List items={identity.match_basis}/></div>{[...result.identity_ambiguities,...identity.ambiguities].length>0&&<div className="mt-3 rounded-lg bg-risk-elevated/10 p-3"><p className="text-xs font-semibold text-risk-elevated mb-1">Identity ambiguities</p><List items={[...new Set([...result.identity_ambiguities,...identity.ambiguities])]}/></div>}</div>}
  {!identity&&<div className="mt-4 rounded-lg bg-risk-elevated/10 p-3 text-xs text-risk-elevated">The merchant identity was not resolved. Treat all other web findings as provisional and do not silently merge entities.</div>}</div>
  <section className="glass rounded-2xl p-5"><h3 className="font-display font-semibold text-ink-100 mb-4">Risk dimensions</h3><div className="grid md:grid-cols-2 gap-3">
    {result.category_fit&&<article className="glass-subtle rounded-xl p-4"><h4 className="font-semibold text-sm text-ink-100">Category fit · <span className="capitalize">{result.category_fit.category_fit.replace(/_/g," ")}</span></h4><p className="text-sm text-ink-300 mt-2">{result.category_fit.explanation}</p><div className="mt-3"><EvidenceCards items={result.category_fit.observed_offerings}/></div></article>}
    {result.restricted_products&&<article className="glass-subtle rounded-xl p-4"><h4 className="font-semibold text-sm text-ink-100">Restricted products</h4><div className="mt-3"><EvidenceCards items={result.restricted_products.indicators}/><List items={result.restricted_products.products_reviewed}/></div></article>}
    {result.reputation&&<article className="glass-subtle rounded-xl p-4"><h4 className="font-semibold text-sm text-ink-100">Reputation & practices</h4><div className="mt-3"><EvidenceCards items={result.reputation.indicators}/><List items={result.reputation.themes}/></div></article>}
    {result.legal_regulatory&&<article className="glass-subtle rounded-xl p-4"><h4 className="font-semibold text-sm text-ink-100">Legal & regulatory</h4><div className="mt-3"><EvidenceCards items={result.legal_regulatory.indicators}/><List items={result.legal_regulatory.jurisdictions_checked}/></div></article>}
  </div>{Object.keys(result.lane_errors||{}).length>0&&<div className="rounded-xl bg-risk-high/10 text-risk-high text-xs p-3 mt-4">Partial lane errors: {Object.entries(result.lane_errors).map(([lane,message])=>`${lane}: ${message}`).join(" · ")}</div>}</section>
  {result.risk_indicators.length>0&&<section className="glass rounded-2xl p-5"><h3 className="font-display font-semibold text-ink-100 mb-3">Supported signals</h3><EvidenceCards items={result.risk_indicators}/></section>}
  <div className="grid md:grid-cols-2 gap-4"><ReportList title="Evidence gaps" items={result.evidence_gaps} empty="Coverage gaps were not reported."/><ReportList title="Recommended next checks" items={result.next_checks} empty="No next checks were returned."/></div>
  <div className="glass-subtle rounded-xl p-4 flex gap-3"><Info className="w-4 h-4 text-tavily-blue shrink-0"/><p className="text-xs text-ink-400 leading-relaxed"><strong className="text-ink-200">Interpretation guardrail:</strong> This is public-web review context, not an underwriting decision. Missing or thin evidence means uncertainty—it must never be interpreted as low risk.</p></div></section>; }
export default function MerchantRiskPage() {
  const [name,setName]=useState(""); const [category,setCategory]=useState(""); const [domain,setDomain]=useState(""); const [country,setCountry]=useState(""); const lanes=useMemo(()=>MERCHANT_LANES,[]); const workflow=useWorkflowStream<MerchantRiskResult>("/api/merchant-risk/stream",lanes); const history=useRunHistory("merchant_risk"); const running=workflow.status === "running";
  const submit=(event:FormEvent)=>{event.preventDefault();if(!name.trim()||!category.trim()||running)return;void workflow.run({merchant_name:name.trim(),category_code:category.trim(),domain:domain.trim()||undefined,country:country.trim()||undefined});};
  useEffect(() => { if (workflow.status === "complete" || workflow.status === "partial") history.refresh(); }, [workflow.status, history.refresh]);
  const load=useCallback(async(id:string)=>{try{const stored=await fetchStoredWorkflow<MerchantRiskResult>(id);workflow.hydrate(stored.result,stored.sources,id);}catch{/* partial stored run */}},[workflow.hydrate]);
  return <main><header className="mb-8"><div className="flex items-center gap-2 text-xs uppercase tracking-[.16em] text-tavily-blue font-semibold"><Fingerprint className="w-4 h-4"/>Merchant risk</div><h1 className="font-display text-3xl font-semibold text-ink-100 mt-3">Resolve identity before reviewing risk</h1><p className="text-sm text-ink-400 mt-1.5 max-w-2xl">Enrich a merchant with current public-web context, explicitly separating identity confidence, supported signals, and evidence gaps.</p></header>
  <div className="grid lg:grid-cols-[320px_1fr] gap-5 items-start"><aside className="glass rounded-2xl p-5 lg:sticky lg:top-24"><form onSubmit={submit} className="space-y-4"><label className="block text-xs font-semibold text-ink-300">Merchant name <span className="text-risk-high">*</span><input value={name} onChange={(e)=>setName(e.target.value)} className={`${fieldClass} mt-1.5`} placeholder="Legal or trading name" required disabled={running}/></label><label className="block text-xs font-semibold text-ink-300">Merchant category <span className="text-risk-high">*</span><input value={category} onChange={(e)=>setCategory(e.target.value)} className={`${fieldClass} mt-1.5`} placeholder="e.g. Supplements retailer" required disabled={running}/></label><label className="block text-xs font-semibold text-ink-300">Domain<input value={domain} onChange={(e)=>setDomain(e.target.value)} className={`${fieldClass} mt-1.5`} placeholder="example.com" disabled={running}/></label><label className="block text-xs font-semibold text-ink-300">Country<input value={country} onChange={(e)=>setCountry(e.target.value)} className={`${fieldClass} mt-1.5`} placeholder="e.g. United States" disabled={running}/></label>{running?<button type="button" onClick={workflow.stop} className="w-full rounded-xl bg-ink-100 text-white px-4 py-2.5 text-sm font-semibold flex gap-2 justify-center"><Square className="w-4 h-4"/>Stop review</button>:<button type="submit" disabled={!name.trim()||!category.trim()} className="w-full rounded-xl bg-tavily-blue text-white px-4 py-2.5 text-sm font-semibold flex gap-2 justify-center disabled:opacity-40"><Play className="w-4 h-4"/>Review public web</button>}</form><p className="text-[10px] text-ink-500 leading-relaxed mt-4">Name and category are required. Domain and country materially improve entity resolution and reduce silent merging.</p></aside>
  <div className="space-y-5"><RunHistory runs={history.runs} activeRunId={workflow.runId} onLoad={load}/>{workflow.error&&<div className="glass rounded-xl p-4 text-sm text-risk-high flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0"/>{workflow.error}</div>}{workflow.status==="cancelled"&&<div className="glass-subtle rounded-xl p-3 text-xs text-ink-400">Review stopped. No conclusion is inferred from unfinished or missing evidence.</div>}<WorkstreamLanes lanes={workflow.lanes} heading="Identity-first review lanes"/>{workflow.result&&<RiskReport result={workflow.result}/>}<SourceList sources={workflow.sources.length?workflow.sources:workflow.result?.sources||[]} title="Public-web sources"/></div></div></main>;
}
